<?php

namespace Database\Seeders;

use App\Enums\DocumentSourceType;
use App\Enums\DocumentStatus;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

/**
 * Seeds a small, realistic library for the given user from the committed sample PDFs in
 * `database/seeders/samples/` (generated by `generate_samples.py`). Idempotent: it skips a
 * user who already has documents, so re-seeding never produces duplicates.
 */
class DemoDocumentsSeeder extends Seeder
{
    public function run(?User $user = null): void
    {
        $user ??= User::query()->firstOrFail();

        if ($user->documents()->exists()) {
            return;
        }

        $samplesDir = database_path('seeders/samples');
        $manifestPath = $samplesDir.'/manifest.json';

        // The manifest ships with the repo; bail out gracefully if it has been removed.
        if (! is_file($manifestPath)) {
            return;
        }

        /** @var list<array{file: string, thumbnail: string, title: string, page_count: int, source_type: string, pages: array<int, array{width: float, height: float}>, size_bytes: int}> $manifest */
        $manifest = json_decode((string) file_get_contents($manifestPath), true);
        $disk = Storage::disk('pdfs');

        foreach ($manifest as $sample) {
            $pdfBytes = file_get_contents($samplesDir.'/'.$sample['file']);

            if ($pdfBytes === false) {
                continue;
            }

            $path = 'documents/'.Str::uuid()->toString().'.pdf';
            $disk->put($path, $pdfBytes);

            $meta = ['pages' => $sample['pages']];

            $thumbnailBytes = @file_get_contents($samplesDir.'/'.$sample['thumbnail']);
            if ($thumbnailBytes !== false) {
                $thumbnailPath = 'thumbnails/'.Str::uuid()->toString().'.png';
                $disk->put($thumbnailPath, $thumbnailBytes);
                $meta['thumbnail_path'] = $thumbnailPath;
            }

            $user->documents()->create([
                'title' => $sample['title'],
                'original_filename' => $sample['file'],
                'disk' => 'pdfs',
                'path' => $path,
                'page_count' => $sample['page_count'],
                'size_bytes' => $sample['size_bytes'],
                'mime' => 'application/pdf',
                'source_type' => DocumentSourceType::from($sample['source_type']),
                'status' => DocumentStatus::Ready,
                'meta' => $meta,
            ]);
        }
    }
}
